#!/bin/sh
#
# PROVIDE: plexupdater
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Add the following to /etc/rc.conf to enable plexupdater:
#
#   plexupdater_enable="YES"
#

. /etc/rc.subr

name="plexupdater"
rcvar="plexupdater_enable"

load_rc_config $name

: ${plexupdater_enable:=NO}
: ${plexupdater_user:=root}
: ${plexupdater_port:=8080}
: ${plexupdater_logfile:=/var/log/plexupdater.log}

command="/usr/local/sbin/plex-updater"
command_args="> ${plexupdater_logfile} 2>&1"
pidfile="/var/run/plexupdater.pid"

start_cmd="plexupdater_start"
stop_cmd="plexupdater_stop"
status_cmd="plexupdater_status"

plexupdater_start()
{
    echo "Starting ${name}."
    /usr/sbin/daemon -f -p ${pidfile} -u ${plexupdater_user} \
        /bin/sh -c "${command} >> ${plexupdater_logfile} 2>&1"
}

plexupdater_stop()
{
    if [ -f "${pidfile}" ]; then
        echo "Stopping ${name}."
        kill $(cat ${pidfile}) && rm -f ${pidfile}
    else
        echo "${name} is not running."
    fi
}

plexupdater_status()
{
    if [ -f "${pidfile}" ] && kill -0 $(cat ${pidfile}) 2>/dev/null; then
        echo "${name} is running as pid $(cat ${pidfile})."
    else
        echo "${name} is not running."
    fi
}

run_rc_command "$1"
