BINARY      = plex-updater
CMD         = ./cmd/plex-updater
INSTALL_DIR = /usr/local/sbin
RCD_DIR     = /usr/local/etc/rc.d

.PHONY: all build install install-rcd clean

all: build

build:
	go build -o $(BINARY) $(CMD)

install: build
	install -m 755 $(BINARY) $(INSTALL_DIR)/$(BINARY)

install-rcd:
	install -m 755 rc.d/plexupdater $(RCD_DIR)/plexupdater

clean:
	rm -f $(BINARY)
