BINARY      = plex-updater
CMD         = ./cmd/plex-updater
INSTALL_DIR = /usr/local/sbin
RCD_DIR     = /usr/local/etc/rc.d

LOCAL_BIN   = /usr/local/bin

.PHONY: all build build-freebsd install install-rcd install-local clean

all: build

# Strip debug info and disable symbol table to reduce binary size.
# CGO_ENABLED=0 ensures a fully static binary with no libc dependency.
LDFLAGS = -s -w
BUILD_FLAGS = -trimpath -ldflags="$(LDFLAGS)"

build:
	GOTOOLCHAIN=local CGO_ENABLED=0 go build $(BUILD_FLAGS) -o $(BINARY) $(CMD)

build-freebsd:
	GOTOOLCHAIN=local CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build $(BUILD_FLAGS) -o $(BINARY) $(CMD)

install: build-freebsd
	install -m 755 $(BINARY) $(INSTALL_DIR)/$(BINARY)

install-rcd:
	install -m 755 rc.d/plexupdater $(RCD_DIR)/plexupdater

install-local:
	install -m 755 scripts/plexctl $(LOCAL_BIN)/plexctl

clean:
	rm -f $(BINARY)
