BINARY     = plex-updater
CMD        = ./cmd/plex-updater
INSTALL_DIR = /usr/local/sbin

.PHONY: all build install clean

all: build

build:
	go build -o $(BINARY) $(CMD)

install: build
	install -m 755 $(BINARY) $(INSTALL_DIR)/$(BINARY)

clean:
	rm -f $(BINARY)
